# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 827e62d18c172a6f70ce9ab1a5a1f971a24571fdfaf8751b222a330ba7bca7b3a9d0afdbf774b2b6146becb545827520b2d5111c7b2e2dd327d20c4cf042da70

test:
  secret_key_base: 09083a8bc4ec71c925375656c1f09a6cf5b899c5a69c8e29235f25f1b79830f752c6db047e9c1acedf29cd9238bd9ebeedf1e77e524c3a39d234840c2eb64cf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
